services:
  - type: web
    name: tata-capital-chatbot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --workers 1 --timeout 120
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.0
      - key: SECRET_KEY
        generateValue: true
      - key: GROQ_API_KEY
        sync: false
    disk:
      name: chatbot-data
      mountPath: /opt/render/project/src
      sizeGB: 1
